begin;
select plan(24);
select has_schema('private','private identity schema exists');
select has_table('public','profiles','profiles exists');
select has_table('private','investor_identities','identities are isolated');
select has_table('public','investment_cycles','cycles exist');
select has_table('public','investments','investments exist');
select has_table('public','bank_receipts','bank receipts exist');
select has_table('public','investment_agreements','agreement receipts exist');
select has_table('public','audit_events','audit log exists');
select has_table('public','jobs','job outbox exists');
select ok((select relrowsecurity from pg_class where oid = 'public.profiles'::regclass),'profiles RLS enabled');
select ok((select relrowsecurity from pg_class where oid = 'public.investments'::regclass),'investments RLS enabled');
select ok((select relrowsecurity from pg_class where oid = 'public.bank_receipts'::regclass),'receipts RLS enabled');
select ok((select relrowsecurity from pg_class where oid = 'public.audit_events'::regclass),'audit RLS enabled');
select function_privs_are('public','request_investment',array['uuid','uuid','integer','uuid','text','bytea'],'service_role',array['EXECUTE'],'service role alone executes reservation function');
select function_privs_are('public','activate_investment',array['uuid','uuid','text','bigint','date','text','boolean','uuid'],'service_role',array['EXECUTE'],'service role alone executes activation function');
select is_empty($$select 1 from information_schema.role_routine_grants where routine_schema='public' and routine_name='activate_investment' and grantee in ('PUBLIC','anon','authenticated')$$,'browser roles cannot activate');
select is_empty($$select 1 from information_schema.role_table_grants where table_schema='private' and table_name='investor_identities' and grantee in ('PUBLIC','anon','authenticated')$$,'browser roles cannot access identity envelope');
select col_type_is('public','investments','principal_ugx','bigint','UGX principal uses whole-shilling bigint');
select col_type_is('public','investments','projected_value_ugx','bigint','UGX projection uses whole-shilling bigint');
select col_type_is('public','investment_cycles','unit_price_ugx','bigint','unit price is bigint');
select throws_ok($$insert into public.investment_cycles(name,opens_at,closes_at,maturity_date,capacity_units,unit_price_ugx,agreement_version_id,created_by) values('bad',now(),now()+interval '1 day',current_date+2,10,1,gen_random_uuid(),gen_random_uuid())$$,'23514',null,'unit price cannot drift');
insert into public.audit_events (action, entity_type, request_id) values ('test.created', 'test', gen_random_uuid());
select throws_ok($$delete from public.audit_events where action = 'test.created'$$,'55000','audit_events records are immutable','audit history cannot be deleted');
select ok((select not public from storage.buckets where id='agreements'),'agreement bucket is private');
select is((select file_size_limit from storage.buckets where id='agreements'),10485760::bigint,'agreement size cap is 10 MB');
select * from finish();
rollback;
